source 'http://rubygems.org'
ruby '2.3.3'

gem 'rails', '4.2.7.1'
gem 'mysql2', '~> 0.3.11'
gem 'sass-rails'
gem 'compass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails', '4.0.4'
gem "jquery-turbolinks"
gem 'turbolinks', '~> 5.0.0'
gem 'jquery-datatables-rails', '~> 3.3.0'
gem 'jquery-ui-rails', '~> 5.0.5'

gem 'jbuilder', '~> 1.2'

gem 'momentjs-rails'
gem 'ruby_dep', ' 1.3.0'
gem "listen", "~> 3.0.0"
gem 'zeroclipboard-rails'
gem 'twitter-bootstrap-rails'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap-timepicker-rails'
gem 'bootstrap-daterangepicker-rails'
gem 'bootstrap-colorpicker-rails'
gem 'icheck-rails'
gem 'select2-rails'
gem 'chosen-rails'
gem 'tzinfo-data'
gem 'ckeditor_rails'
gem 'crummy'
gem 'maskedinput-rails'
gem 'paperclip'
gem 'jquery-fileupload-rails'
gem 'jquery-validation-rails'
gem 'devise'
gem 'slim-rails', '3.1.1'
gem 'cancan'
gem 'role_model'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'whenever', :require => false
# gem 'monetize'
gem 'money-rails'

gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'
group :development do
  gem 'guard-rspec'
  gem 'guard-livereload'
  gem 'guard-zeus'
  gem 'capistrano'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'parallel_tests'
  gem 'byebug', '~> 10.0', '>= 10.0.2'
end

group :test, :darwin do
  gem 'rb-fsevent'
 
end




